### ISSUE TITLE
Javascript en archivo excel generado

### ISSUE THREAD

**Issue by joseluisq** [juanlopezdev/YunhoDBExport#10]
Bro, he visto que se genera un pequeño código javascript `window.close` justo al final del reporte en el archivo excel. Pienso se debería realizar alguna validación al respecto.

![image](https://cloud.githubusercontent.com/assets/1700322/9609940/2642ca08-509c-11e5-96c5-6c005d8457c8.png)

Saludos.

**Comment by juanlopezdev** [comment]
Listo Bro :+1: 
He quitado ese bug.
d26551cb423fa999d0df4e0aa2d033b468fc4de4

**Comment by joseluisq** [comment]
Bien :+1:
