### ISSUE TITLE
Problema de codificación de caracteres

### ISSUE THREAD

**Issue by joseluisq** [juanlopezdev/YunhoDBExport#2]
Bro, los caracteres especiales no se visualizan correctamente al exportar a Excel.
Adjunto captura:

![image](https://cloud.githubusercontent.com/assets/1700322/6232489/4be11cd4-b69a-11e4-968d-bd29f010f12d.png)

Saludos

**Comment by juanlopezdev** [comment]
Hola, ya corregí lo solicitado...
https://github.com/JuanLopezDev/YunhoDBExport/commit/be413d3cb1d4686dd0d438f5b7291f652fed929a

Gracias

**Comment by joseluisq** [comment]
Genial bro funciona :+1: 
Gracias!

**Comment by joseluisq** [comment]
Corregido https://github.com/juanlopezdev/YunhoDBExport/pull/17
