### ISSUE TITLE
Agregar soporte para formato de fecha (mejora)

### ISSUE THREAD

**Issue by joseluisq** [juanlopezdev/YunhoDBExport#3]
Bro, es necesario agregar alguna máscara para dar formato a las fechas.
Aquí un [Gist](https://gist.github.com/joseluisq/9561383) con una función que podría ser de ayuda.

Saludos

**Comment by joseluisq** [comment]
@JuanLopezDev cuando puedes revisar esto?

**Comment by juanlopezdev** [comment]
Hola Jose Luis ya lo he actualizado, en la carpeta "examples" en el archivo "example.php" esta.
Este es el commit 43b5f94c88c0221878bdc85d0dd0fd6b8a2b355b

**Comment by joseluisq** [comment]
:+1:
