### ISSUE TITLE
Validar opción label en array

### ISSUE THREAD

**Issue by joseluisq** [juanlopezdev/YunhoDBExport#5]
Es necesario validar la opción `label` cuando se pasa como parámetro dentro de un array. 
Actualmente esto causa error:

``` php
<?php
// Mapeo de campos para cabecera
$fields = array(
  'id' => 'ID',
  'newsletter' => array(
    'label' => 'Boletín'
  )
);
```

Saludos

**Comment by juanlopezdev** [comment]
Listo Jose Luis, ahora si deseas puedes poner una etiqueta label dentro de un array.
b83b3c7fb0dc0095498fd559453cdb7470d6dea9

**Comment by joseluisq** [comment]
@JuanLopezDev bacan :+1:
